# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"
  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # Provide unicode arrows based on VIM hjkl commands
  - triggers: ["hh\t", "::hh"]
    label: "Provide a left-pointing arrow"
    replace: "‚Üê"

  - triggers: ["ll\t", "::ll"]
    label: "Provide a right-pointing arrow"
    replace: "‚Üí"

  - triggers: ["jj\t", "::jj"]
    label: "Provide a down-pointing arrow"
    replace: "‚Üì"

  - triggers: ["kk\t", "::kk"]
    label: "Provide an up-pointing arrow"
    replace: "‚Üë"

  - triggers: ["hl\t", "::hl"]
    label: "Provide a left & right pointing arrow"
    replace: "‚ü∑"

  - triggers: ["arrow\t", "::arrow"]
    label: "Provide a list of arrows"
    replace: "{{arrowList.arrow}}"
    vars:
      - name: "arrowList"
        type: form
        params:
          layout: "[[arrow]]"
          fields:
            arrow:
              type: list
              default: ‚Üí
              values:
                - ‚Üí
                - ‚Üê
                - ‚Üì
                - ‚Üë
                - ‚ü∑
                - ‚Üñ
                - ‚Üó
                - ‚Üò
                - ‚Üô
                - ‚Ü™
                - ‚Ü©

  # Provide specific signs
  - triggers: ["diff\t", "::diff", "inqu\t", "::inqu"]
    label: "Provide an inequality math sign"
    replace: "‚â†"

  - triggers: ["alpha\t", "::alpha"]
    label: "Provide a 'ùõÇ' (alpha) greek sign"
    replace: "ùõÇ"

  - triggers: ["beta\t", "::beta"]
    label: "Provide a 'ùõÉ' (beta) greek sign"
    replace: "ùõÉ"

  - triggers: ["delta\t", "::delta"]
    label: "Provide a 'ùö´' (delta) greek sign"
    replace: "ùö´"

  - triggers: ["gamma\t", "::gamma"]
    label: "Provide a 'ùõÑ' (gamma) greek sign"
    replace: "ùõÑ"

  # Provide bullets and dashes
  - trigger: "dash\t"
    label: "Provide a dash bullet, followed by a tab"
    replace: "‚Äî\t"

  - trigger: "::dash"
    label: "Provide a dash bullet"
    replace: "‚Äî"

  - trigger: "bull\t"
    label: "Provide a dot bullet, followed by a tab"
    replace: "‚Ä¢\t"

  - trigger: "::bull"
    label: "Provide a dot bullet"
    replace: "‚Ä¢"

  - trigger: "rbul\t"
    label: "Provide a right pointing triangle bullet, followed by a tab"
    replace: "‚ñ∂\t"

  - trigger: "::rbul"
    label: "Provide a right pointing triangle bullet"
    replace: "‚ñ∂"

  - trigger: "lbul\t"
    label: "Provide a left pointing triangle bullet, followed by a tab"
    replace: "\t‚óÄ"

  - trigger: "::lbul"
    label: "Provide a left pointing triangle bullet"
    replace: "‚óÄ"

  # Correct the most common english mistakes
  - trigger: ".lenght"
    label: "Provide '.length'"
    replace: ".length"

  # Provide french accentuated words
  - triggers: ["cout\t", "::cout"]
    label: "Provide 'co√ªt'"
    replace: "co√ªt"
    propagate_case: true

  - trigger: "cout"
    label: "Provide 'co√ªt'"
    replace: "co√ªt"
    propagate_case: true
    word: true

  - triggers: ["couts\t", "::couts"]
    label: "Provide 'co√ªts'"
    replace: "co√ªts"
    propagate_case: true

  - trigger: "couts"
    label: "Provide 'co√ªts'"
    replace: "co√ªts"
    propagate_case: true
    word: true

  - triggers: ["francais\t", "::francais"]
    label: "Provide 'fran√ßais'"
    replace: "fran√ßais"
    propagate_case: true

  - trigger: "francais"
    label: "Provide 'fran√ßais'"
    replace: "fran√ßais"
    propagate_case: true
    word: true

  - triggers: ["meme\t", "::meme"]
    label: "Provide 'm√™me'"
    replace: "m√™me"
    propagate_case: true

  - trigger: "meme"
    label: "Provide 'm√™me'"
    replace: "m√™me"
    propagate_case: true
    word: true

  - triggers: ["reponse\t", "::reponse"]
    label: "Provide 'r√©ponse'"
    replace: "r√©ponse"
    propagate_case: true

  - trigger: "reponse"
    label: "Provide 'r√©ponse'"
    replace: "r√©ponse"
    propagate_case: true
    word: true

  # Provide currency symbols
  - triggers: ["eur\t", "::eur"]
    label: "Provide the EUR currency sign"
    replace: "‚Ç¨"

  - triggers: ["gbp\t", "::gbp"]
    label: "Provide the GBP/pound currency sign"
    replace: "¬£"

  - triggers: ["usd\t", "::usd"]
    label: "Provide the USD/dollar currency sign"
    replace: "$"

  - triggers: ["jpy\t", "::jpy"]
    label: "Provide the JYP currency sign"
    replace: "¬•"

  - triggers: ["rmb\t", "::rmb", "cny\t", "::cny"]
    label: "Provide the CNY currency sign"
    replace: "ÂÖÉ"

  - triggers: ["krw\t", "::krw"]
    label: "Provide the KRW currency sign"
    replace: "‚Ç©"

  - triggers: ["inr\t", "::inr"]
    label: "Provide the INR currency sign"
    replace: "‚Çπ"

  - triggers: ["rub\t", "::rub"]
    label: "Provide the RUB currency sign"
    replace: "‚ÇΩ"

  - triggers: ["thb\t", "::thb"]
    label: "Provide the THB currency sign"
    replace: "‡∏ø"

  - triggers: ["btc\t", "::btc"]
    label: "Provide the Bitcoin currency sign"
    replace: "‚Çø"

  - triggers: ["eth\t", "::eth"]
    label: "Provide the Ethereum currency sign"
    replace: "Œû"

  # Provide emoji color dots such as üî¥, üü†, üü°, üü¢ etc.
  - triggers: ["red\t", "::red"]
    label: "Provide a 'red dot' emoji"
    replace: "\U0001F534"

  - triggers: ["orange\t", "::orange"]
    label: "Provide a 'orange dot' emoji"
    replace: "\U0001F7E0"

  - triggers: ["yellow\t", "::yellow"]
    label: "Provide a 'yellow dot' emoji"
    replace: "\U0001F7E1"

  - triggers: ["green\t", "::green"]
    label: "Provide a 'green dot' emoji"
    replace: "\U0001F7E2"

  - triggers: ["blue\t", "::blue"]
    label: "Provide a 'blue dot' emoji"
    replace: "\U0001F535"

  - triggers: ["violet\t", "::violet", "purple\t", "::purple"]
    label: "Provide a 'purple dot' emoji"
    replace: "\U0001F7E3"

  - triggers:
      ["brown\t", "::brown", "maroon\t", "::maroon", "marron\t", "::marron"]
    label: "Provide a 'brown dot' emoji"
    replace: "\U0001F7E4"

  - triggers: ["black\t", "::black"]
    label: "Provide a 'black dot' emoji"
    replace: "\U000026AB"

  - triggers: ["white\t", "::white"]
    label: "Provide a 'white dot' emoji"
    replace: "\U000026AA"

  # Provide emoji status
  - triggers: ["warn\t", "::warn", "warning\t", "::warning"]
    label: "Provide a 'triangular warning sign' emoji"
    replace: "‚ö†"

  - triggers: ["check\t", "::check"]
    label: "Provide a 'positive green check' emoji"
    replace: "‚úîÔ∏è"

  - triggers: ["cross\t", "::cross"]
    label: "Provide a 'negative red cross' emoji"
    replace: "‚ùå"

  - triggers: ["thup\t", "::thup"]
    label: "Provide a 'thumb up' emoji"
    replace: "üëç"

  - triggers: ["thdw\t", "::thdw"]
    label: "Provide a 'thumb down' emoji"
    replace: "üëé"

  - triggers: ["happy\t", "::happy", ":)\t", ":-)\t"]
    label: "Provide a 'happy face' emoji"
    replace: "üòÑ"

  - triggers: ["sad\t", "::sad", ":(\t", ":-(\t"]
    label: "Provide a 'sad face' emoji"
    replace: "üòû"

  # But matches can also be dynamic:
  # Print the current date
  - triggers: ["date\t", "::date"]
    replace: "{{mydate}}"
    label: "Insert today's date such as 05-Jan-2022"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d-%b-%Y"

  # Print the output of a shell command
  - triggers: ["shell\t", "::shell"]
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/
  # Print "Hello Simple" greetings for email communications
  - triggers: ["hs\t", "::hs"]
    replace: "Hello,\nI hope this message finds you well.\nI am contacting you because "
    label: "Provide a simple introduction for email communications"

  # Print "Hello Simple" greetings for email communications
  - triggers: ["hm\t", "::hm"]
    replace: "Hello,\nI am contacting you because "
    label: "Provide a minimalistic introduction for email communications"

  # Print "Hello Thank you" greetings for email communications
  - triggers: ["ht\t", "::ht"]
    replace: "Hello,\nThank you for your message, "
    label: "Provide a 'thank you for your message' for email communications"

  # Print "Hello Thank you" greetings for email communications
  - triggers: ["thpt\t", "::thpt"]
    replace: "Thank you for your input"
    propagate_case: true
    label: "Provide a 'thank you for your input' for email communications"

  - triggers: ["ths\t", "::ths"]
    replace: "Thank you.\nSincerely,"
    propagate_case: true
    label: "Provide a 'Thank you,\nSincerely' for email communications"

  # Provide a list of greetings for email communications
  - triggers: ["th*\t", "::th*"]
    label: "Provide ending salutations for email communications"
    replace: "{{greetingsList.greetings}}"
    vars:
      - name: "greetingsList"
        type: form
        params:
          layout: "[[greetings]]"
          fields:
            greetings:
              type: list
              default: "Thank you.\nSincerely,"
              values:
                - "Thank you.\nSincerely,"
                - "Thank you.\nHave a nice day,"
                - "Thank you.\nHave a nice weekend,"
                - "Cordialement,"

  # Provide accentuated letters for French
  - triggers: ["acc\t", "::acc"]
    label: "Provide a list of French accents"
    replace: "{{accentList.accent}}"
    vars:
      - name: "accentList"
        type: form
        params:
          layout: "[[accent]]"
          fields:
            accent:
              type: list
              default: √©
              values:
                - √©
                - √®
                - √™
                - √†
                - √π
                - √ß
                - √Ø

  # Provide a list Vue.js snippets
  - trigger: "::vrouter"
    label: "Provide a standard import of the Vue Router"
    replace: "import { useRouter } from 'vue-router';\nconst router = useRouter();"

  - trigger: "::vstore"
    label: "Provide a standard import of the Vue userStore"
    replace: "import { useUserStore } from '../../stores/UserStore.js';\nconst userStore = useUserStore();"

  - trigger: "::vimport"
    label: "Provide a standard import of the Vue reactivity"
    replace: "import {\nref,\nreactive,\ncomputed,\nwatch,\nonBeforeMount,\nonMounted,\nonBeforeUpdate,\nonUpdated,\nonBeforeUnmount,\nonUnmounted\n} from 'vue';"

  - trigger: "::vwatch"
    label: "Provide a standard watcher syntax of Vue"
    replace: "watch(objToWatch, (newValue, oldValue) => {\n  // fires on nested property mutations\n});"

  # Provide a list JavaScript snippets
  - trigger: "::jsreduce"
    label: "Provide a JavaScript reduce array method"
    replace: "const sumWithInitial = array1.reduce(\n  (accumulator, currentValue) => accumulator + currentValue,\n  initialValue,\n);"

  - trigger: "::jsreadfile"
    label: "Provide a Node.js code snippet to read files and provide array of lines"
    replace: "// Import the Node.js file system\nconst fs = require('fs');\n\n// Use the file system to read the text file and encode it in UTF-8\nconst fileContent = fs.readFileSync('fileName.txt', 'utf8');\n\n// Create an array using the array.split() method\n// Split is performed using the carriage return as a separator\nconst arrayOfLines = fileContent.split('\\n').map(line => line.replace(/\\r$/, '')).filter((value) => value.length > 0);"
